# Generated by Django 5.0.2 on 2024-02-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vegetable',
            new_name='Vegetables',
        ),
    ]
