# Generated by Django 5.0.1 on 2024-02-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Price_per_Kg', models.IntegerField()),
                ('Stock_in_Kg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Price_per_Kg', models.IntegerField()),
                ('Stock_in_Kg', models.IntegerField()),
            ],
        ),
    ]
