# Generated by Django 5.0.1 on 2024-02-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groceries', '0005_alter_fruits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/vegetable_images/'),
        ),
    ]
